name: CI/CD Workflow

on:
    push:
    
    # workflow_dispatch:

jobs:
    Image_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v3
            - name: Image Build and Push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
              env:
                IMAGE_NAME: node-app
                IMAGE_TAG: latest